services:
  ros2:
    build: .
    image: ros2-dev
    container_name: ros2_container
    network_mode: host
    volumes:
      - ./ros_workspace:/root/ros_workspace
    working_dir: /root/ros_workspace
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=host.docker.internal:0
      - LIBGL_ALWAYS_INDIRECT=0
      - LIBGL_ALWAYS_SOFTWARE=1
    command: bash -c "/root/.colcon_ignore_setup.sh && bash"

